### PR TITLE
Using normalized AOs now

### PR DESCRIPTION
**Pull request by scemama**

### CODE REVIEW

**Comment by TApplencourt** [comment]
You need, to source quantum_package.rc in the bat file.

**Comment by TApplencourt** [comment]
```
The command "source ./quantum_package.rc ; ninja" exited with 0.
0.02s$ source ./quantum_package.rc ; cd ocaml ; make ; cd -
cp /home/travis/build/LCPQ/quantum_package/install/EZFIO/Ocaml/ezfio.ml .
ocamlbuild -j 0 -syntax camlp4o -cflags "-g -warn-error A" -lflags "-g -warn-error A"  qptypes_generator.byte  -use-ocamlfind 
/bin/sh: 1: ocamlbuild: not found
make: *** [qptypes_generator.byte] Error 127
/home/travis/build/LCPQ/quantum_package
```

Maybe a probleme with the cache

**Comment by TApplencourt** [comment]
I find the bug. I Try to fix it.
GCC version 4.6 too old. GCC >= 4.6 required.

**Comment by TApplencourt** [comment]
Juste put a $ in front of the "i" in `$QP_ROOT/install/script/nstall_ocam.sh`, ligne 26

Or use mine (more robust `check_version` option)

```
#!/bin/bash

cd ..
QP_ROOT=$PWD
cd -

# Normal installation
PACKAGES="core cryptokit ocamlfind sexplib ZMQ"

# Needed for ZeroMQ
export C_INCLUDE_PATH="${QP_ROOT}"/lib:"${C_INCLUDE_PATH}"
export LIBRARY_PATH="${QP_ROOT}"/lib:"${LIBRARY_PATH}"
export LD_LIBRARY_PATH="${QP_ROOT}"/lib:"${LD_LIBRARY_PATH}"

# return 0 if program version is equal or greater than check version
check_version () {
    if [[ $1 == $2 ]]
    then
        return 0
    fi
    local IFS=.
    local i ver1=($1) ver2=($2)
    # fill empty fields in ver1 with zeros
    for ((i=${#ver1[@]}; i<${#ver2[@]}; i++))
    do
        ver1[i]=0
    done
    for ((i=0; i<${#ver1[@]}; i++))
    do
        if [[ -z ${ver2[i]} ]]
        then
            # fill empty fields in ver2 with zeros
            ver2[i]=0
        fi
        if ((10#${ver1[i]} > 10#${ver2[i]}))
        then
            return 1
        fi
        if ((10#${ver1[i]} < 10#${ver2[i]}))
        then
            return 2
        fi
    done
    return 0
}


i=$(gcc -dumpversion)

check_version 4.6 $i 
if [[ $? == 1 ]]
then
   echo "GCC version $(gcc -dumpversion) too old. GCC >= 4.6 required."
   exit 1
fi


if [[ -d ${HOME}/.opam ]]
then
  source ${HOME}/.opam/opam-init/init.sh > /dev/null 2> /dev/null || true
fi

cd Downloads || exit 1
chmod +x  ocaml.sh || exit 1

echo N | ./ocaml.sh ${QP_ROOT}/bin/ || exit 1

${QP_ROOT}/bin/opam config setup -a -q || exit 1

export LD_LIBRARY_PATH=${QP_ROOT}/lib:${LD_LIBRARY_PATH}
export LIBRARY_PATH=${QP_ROOT}/lib:${LIBRARY_PATH}
export C_INCLUDE_PATH=${QP_ROOT}/lib:${C_INCLUDE_PATH}
source ${HOME}/.opam/opam-init/init.sh > /dev/null 2> /dev/null || true


NCPUs=$(cat /proc/cpuinfo  | grep -i  MHz | wc -l)
${QP_ROOT}/bin/opam install -j ${NCPUs} ${PACKAGES} -y -q || exit 1

rm -f ../_build/ocaml.log
exit 0
```

**Comment by scemama** [comment]
Amazing!!!

**Pull request merged**
