### PR TITLE
Fixed parallelism

### PR DESCRIPTION
**Pull request by scemama**
Don't merge before travis is OK pls

### CODE REVIEW

**Comment by TApplencourt** [comment]
Do you know why Travis stop running?
We should merge this PR at some point, so other people can benefit from the amazing ameliorations : )

**Comment by TApplencourt** [comment]
```
['/home/travis/build/LCPQ/quantum_package/plugins/mrcc'] is not a module and/or has not a `README.rst` file inside
Aborting...
```

Sorry ><

**Comment by TApplencourt** [comment]
Oh My God ! Should we merge? 🍂

**Comment by scemama** [comment]
I am running some tests on theta. If everything is OK, we can merge....

Anthony

**Comment by scemama** [comment]
Still a little problem to fix. I need a few more days. :-(

Anthony

**Comment by TApplencourt** [comment]
Let's merge? 👍

**Comment by scemama** [comment]
I still have a few bugs left. Give me till the end of the week...

**Comment by TApplencourt** [comment]
If Travis didn't catch the bugs, are those really bugs? :)

**Comment by scemama** [comment]
Yes, sadly :-(

Anthony

**Pull request closed without merging**
