### PR TITLE
Solves True/true problem

### PR DESCRIPTION
**Pull request by scemama**

### CODE REVIEW

**Comment by TApplencourt** [comment]
It's not a fix but a work around.

I don't understand why True is not valide. I will investigate tomorrow.
This bug bother me really hard!
Le 19 avr. 2015 17:18, "Anthony Scemama" <notifications@github.com> a
écrit :

**Comment by scemama** [comment]
In Ocaml, true is "true" and not "True". Converting the string "True" to a boolean gives an error.
All the true and false values in the files should be in lowercase. All types should be capitalized (true and false are not types but values).
:tada:

**Comment by TApplencourt** [comment]
Yeah, i know. But I'm pretty sur I am doing this.
The function `is bool` in `ei_handler` is designed to do the conversion.

It's a high level utility. The user can put `.TRue.`, if he wants.

So, I will find the bug. And kill it! :angry:
Le 20 avr. 2015 00:36, "Anthony Scemama" <notifications@github.com> a
écrit :

**Comment by TApplencourt** [comment]
Ok, i find the bug (thanks to your merge :))

It is the doublon (?) between WILL_BE_DELETED and  `EZFIO.cfg`. I will
remove all of it.

It is a nice morning ! :happy;


2015-04-20 7:58 GMT+02:00 Thomas Applencourt <t.applencourt@gmail.com>:

**Pull request merged**
